### PR TITLE
fix: link to commit hash for external deployment

### LINKED ISSUE #72: proposal: Allow option to mirror current commit message on external repo commit message
When using `EXTERNAL_REPOSITORY`, the only option for the commit message is currently
```
COMMIT_MESSAGE="Automated deployment: $(date -u) ${GITHUB_SHA}"
```
It would be awesome if we could have the option to have the message of the commit we're currently deploying as the commit message for the external repo, in order to see on the external repo what we've just deployed, instead of the current generic message.

### PR DESCRIPTION
**Pull request by peaceiris**
Close #72

### CODE REVIEW

**Comment by peaceiris** [comment]
Test: https://github.com/peaceiris/test-hugo-external-repo/commit/4116f6ab59ebad18b92d0da609d531f85a4aa262

**Comment by peaceiris** [comment]
@fabiosangregorio

Please try to use `peaceiris/actions-gh-pages@v2.8.1-0`

**Comment by fabiosangregorio** [comment]
Thank you so much for the responsiveness!
I understand you linked the origin repo's commit message in the external repo's commit message. Unfortunately, as in my use case i deploy from a private repo to an external public repo, I can only see the commit message if I'm logged into my Github account (i.e. other people visiting my external repo can't see what I've changed in that commit).

Would you consider adding the commit description to the external repo's commit message? Or is it bad practice?

Thank you again for the quick response.

**Comment by peaceiris** [comment]
I got it. Open #74

**Comment by peaceiris** [comment]
This change has enhanced this action. Thank you @fabiosangregorio

**Pull request merged**
