### PR TITLE
feat: Add tagName and tagMessage options

### LINKED ISSUE #76: proposal: Create Tag on Commit
**Is your feature request related to a problem? Please describe.**
I'd like to tag specific versions of my `gh-pages` branch programmatically (in my case, based on `package.json` version)

**Describe the solution you'd like**
I'd like an option to add a tag with a specified name on commit.

**Describe alternatives you've considered**
Manually - PITA.

**Additional context**
I'm thinking I'd like to be able to use this like so:

```yml
- name: Tagged Deploy
  env:
    ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    PUBLISH_BRANCH: gh-pages
    PUBLISH_DIR: ./public
    CREATE_TAG: ${{ <expression> }}
```

Where expression might load some values from other steps or combine readily available job information.

Other options for forcing the overwrite of an existing tag or not might make sense too.

### PR DESCRIPTION
**Pull request by peaceiris**
Close #76 

- [x] Update readme.md

### CODE REVIEW

**Comment by peaceiris** [comment]
Test

- repo: https://github.com/peaceiris/nextjs-test
- workflow file: https://github.com/peaceiris/nextjs-test/blob/v0.1.2/.github/workflows/gh-pages.yml

Commands on a local machine:

```console
npm version patch
git push origin "v$(jq -r '.version' ./package.json)"
```

**Comment by peaceiris** [comment]
@cinderblock
Please test `peaceiris/actions-gh-pages@v2.10.0-0`.

**Comment by cinderblock** [comment]
Nicely done! Haven't had time to test yet. What about an option to force/replace an existing tag?

**Comment by peaceiris** [comment]
Do you have any use case of force/replace options? I have no idea and it looks dangerous for me.

**Comment by cinderblock** [comment]
Maybe a mistake was made an someone wants to replace a wrong tag.

Yes, it is "dangerous", and that's why it should not be enabled by default. But it should be an option.

It's just the `--force` option on `git tag`.

**Comment by peaceiris** [comment]
Add `tagOverwrite: true` to `peaceiris/actions-gh-pages@v2.10.0-1`.

**Comment by peaceiris** [comment]
v2.10.0 has been released and the stable tag v2 updated.
Thank you!

https://github.com/peaceiris/actions-gh-pages/releases/tag/v2.10.0

**Pull request merged**
