### PR TITLE
feat: Add INPUT_FORCEORPHAN

### PR DESCRIPTION
**Pull request by peaceiris**
Pull Request for #42

- [x] Add new option `INPUT_FORCEORPHAN`
- [x] Release `v2.6.0-rc0`
- [x] Update docs
- [x] Test
- [ ] Release `v2.6.0`
- [ ] merge this into master

### CODE REVIEW

**Comment by peaceiris** [comment]
@ruzickap Could you try the following?

```yaml
    - name: Deploy
      uses: peaceiris/actions-gh-pages@force-orphan
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./your_dir
      with:
        forceOrphan: true
```

**Comment by ruzickap** [comment]
Thanks a lot @peaceiris. That's exactly what I was looking for.
It works fine for me.

Is there any estimation when it will be released as part of "official" `actions-gh-pages` ?

Thank you...

**Comment by peaceiris** [comment]
Sure. I know there is a demand for this feature. After some testing, I will merge this change and release `v2.6.0`. Thank you.

**Comment by peaceiris** [comment]
@ruzickap 
I released `v2.6.0-rc0`. It is better to use `v2.6.0-rc0` instead of the `force-orphan` branch. (This branch will be deleted after merging.) And, please wait for the release `v2.6.0`.

**Comment by danopz** [comment]
Working fine for me here, thank you for that nice action :+1:

**Comment by peaceiris** [comment]
This change has been merged and the `v2.6.0` has been released. Thanks all.

**Pull request merged**
