### PR TITLE
fix: set commit author as local config

### LINKED ISSUE #151: Avoid to use `git config --global` for setting user name and email
Thank you very much for the actions.

**Is your feature request related to a problem? Please describe.**
For setting committer information, currently `git config --global` is used. However, the command affects globally.

https://github.com/peaceiris/actions-gh-pages/blob/fd6e5fc7ce07cfd94a2311f7ac112bd797c3aee7/src/git-utils.ts#L106-L129

**Describe the solution you'd like**
`git commit --author="myname <myemail>" ...` This minimizes the effects.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by peaceiris**
Close #151

Co-authored-by: Ryo Ota <nwtgck@nwtgck.org>

### CODE REVIEW

**Comment by peaceiris** [comment]
@nwtgck Give me your review.

**Comment by nwtgck** [comment]
@peaceiris Thanks.

I also think without-`--global` is better. However, `git config` still change the environment of current working directory. So, I think using `git commit --author="myname <myemail>" ...` is better to minimize the effects.

**Comment by peaceiris** [comment]
I tried to use `git commit --author` and got this problem: https://github.com/peaceiris/actions-gh-pages/runs/501948622?check_suite_focus=true#step:13:94

Screen Shot 2020-03-12 at 8 50 32

We can use a local git repository config (`.git/config`) instead of `git commit --author`.

This action creates a temporary directory, copies `publish_dir/**` under the directory, and uses it as a local git repository for each deployment. The following steps will not be broken by this action.

**Comment by nwtgck** [comment]
@peaceiris Very great! I understand `git commit --author` causes `Please tell me who you are.` and the actions creates a temporary directory.

**Comment by peaceiris** [comment]
Thank you.

**Pull request merged**
