### PR TITLE
feat: Add username and useremail options

### LINKED ISSUE #66: Proposal: Add option to define custom Git user.name and user.email
**Describe the bug**
I want to change the user.name and user.email, such as 'test-user' and 'test-user@gmail.com' for deploy commits.

**Expected behavior**
Assume this is the commit list:

```bash
Commits on Dec 24, 2019
  chore: deploy to gh-pages      
  `orzyyyy` committed 17 minutes ago
      |
      ---------------------->   this one is not the expected user
```
---

```bash
Commits on Dec 24, 2019
  chore: deploy to gh-pages                        
    `test-user` committed 17 minutes ago
      |
      ---------------------->   this one is expected
```

**Your YAML file**
```yaml
name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set username and email
        run: |
          git config --global user.name "test-user"
          git config --global user.email test-user@gmail.com

      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: debug
        run: git config --list

      - name: deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
        with:
          emptyCommits: false

```

### PR DESCRIPTION
**Pull request by peaceiris**
Close #66

### CODE REVIEW

**Comment by peaceiris** [comment]
@orzyyyy 
Please try the following.

```yaml
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.8.0-0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
      with:
        username: "iris"
        useremail: "iris@peaceiris.com"
```

**Comment by orzyyyy** [comment]
Is this released now?

**Comment by peaceiris** [comment]
`v2.8.0-0` is a pre-release. After testing and documentation updating, this change will be merged and `v2.8.0` released.

**Comment by orzyyyy** [comment]
It works, thanks!

Ref: https://github.com/orzyyyy/memo/commits/gh-pages
https://github.com/orzyyyy/memo/commit/be0a51f20afbf102bf592106251ecd6b6c6b59a1/checks?check_suite_id=372447456

**Pull request merged**
